#
# Author:: Vianney Foucault (<vianney.foucault@gmail.com>)
# Copyright:: Copyright (c) 2015 The Author
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# 
### HMC Part
#
:hmc:
  :host: 'hmchost'
  :port: '22'
  :user: 'hscroot'
  :password: 'abc123'
## NIM Part
:nim:
  :host: 'nimhost'
  :port: '22'
  :user: 'root'
  :password: 'rootroot'
  :nimobjects: 
    - 'group=master_713'
    - 'resolv_conf=fr_RESOLV'
    - 'file_res=FR_DC_FR'
## Misc Part
#
:misc: 
  :reportdir: '~/knife-power-reports/'
  :configdir: '~/knife-power-configs/'
## Array Friendly names part
#
:friendlynames:
  :storagearray: 
    13C89:  'SA_DC1'
    12A6B:  'SA_DC2'
